name: bioresilient
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - mafft
  - orthofinder
  - diamond
  - iqtree
  - hyphy
  - blast
  - pip
  - pip:
    - sqlalchemy==2.0.23
    - alembic==1.13.1
    - fastapi==0.109.0
    - uvicorn==0.27.0
    - biopython==1.84
    - requests==2.31.0
    - pydantic==2.6.0
    - pandas==2.2.0
    - numpy>=1.26.0
    - pytest==8.1.0
    - psycopg2-binary==2.9.9
    - python-dotenv==1.0.0
    - pyyaml==6.0.1
    - scipy==1.13.0
    - tqdm==4.66.0
    - aiohttp==3.9.1
    - lxml==4.9.3
    - python-multipart==0.0.6
    - boto3
    - brotli
    - torch
    - fair-esm
